#ifndef MOUSOIDCORE_GLOBAL_HPP
#define MOUSOIDCORE_GLOBAL_HPP

#include <QtCore/qglobal.h>

#if defined(MOUSOIDCORE_LIBRARY)
#  define MOUSOIDCORESHARED_EXPORT Q_DECL_EXPORT
#else
#  define MOUSOIDCORESHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // MOUSOIDCORE_GLOBAL_HPP
